abranch22
gudmdharalds-a8c/testing123 pull request #563
Opened 2021-03-12 13:41 UTC by gudmdharalds

2021-03-12 13:48 UTC, gudmdharalds-a8c commented
This Pull Request has been added to the VIP review queue and will be reviewed and updated by a member of the VIP code review team (as per your SLA). In the meantime, please review and respond to any automated feedback generated by the @wpcomvip-vipgoci-bot.<br><br> If you’d like to request an urgent VIP review, please add the VIP urgent review label or reply to this PR with a comment containing the word <code>urgent</code> to notify the entire VIP code review team.

2021-03-12 13:50 UTC, gudmdharalds-a8c requested changes
**phpcs** scanning turned up:

:no_entry_sign: 1 error 

***


This bot provides automated PHP Linting and PHPCS scanning, read more [here](https://vip.wordpress.com/documentation/the-vip-code-analysis-bot/).

2021-03-12 13:50 UTC, gudmdharalds-a8c commented on bla-8.php
> +echo "foo" . time() . PHP_EOL;
:no_entry_sign: **Error( severity 5 )**: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'time' (*WordPress.Security.EscapeOutput.OutputNotEscaped*).

2021-03-23 18:02 UTC, gudmdharalds-a8c requested changes
**phpcs** scanning turned up:

:no_entry_sign: 8 errors 

***


This bot provides automated PHP Linting and PHPCS scanning, read more [here](https://vip.wordpress.com/documentation/the-vip-code-analysis-bot/).

2021-03-23 18:02 UTC, gudmdharalds-a8c commented on bla-7.php
> +echo "foo" . time() . PHP_EOL;
:no_entry_sign: **Error( severity 5 )**: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'time' (*WordPress.Security.EscapeOutput.OutputNotEscaped*).

2021-03-23 18:02 UTC, gudmdharalds-a8c commented on bla-7.php
> +echo "foo" . time() . PHP_EOL;
:no_entry_sign: **Error( severity 5 )**: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'time' (*WordPress.Security.EscapeOutput.OutputNotEscaped*).

2021-03-23 18:02 UTC, gudmdharalds-a8c commented on bla-7.php
> +echo "foo" . time() . PHP_EOL;
:no_entry_sign: **Error( severity 5 )**: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'time' (*WordPress.Security.EscapeOutput.OutputNotEscaped*).

2021-03-23 18:02 UTC, gudmdharalds-a8c commented on bla-7.php
> +echo '92';echo "foo" . time() . PHP_EOL;
:no_entry_sign: **Error( severity 5 )**: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'time' (*WordPress.Security.EscapeOutput.OutputNotEscaped*).

2021-03-23 18:02 UTC, gudmdharalds-a8c commented on bla-7.php
> +echo '1110';echo "foo" . time() . PHP_EOL;
:no_entry_sign: **Error( severity 5 )**: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'time' (*WordPress.Security.EscapeOutput.OutputNotEscaped*).

2021-03-23 18:02 UTC, gudmdharalds-a8c commented on bla-7.php
> +echo '2780';echo "foo" . time() . PHP_EOL;
:no_entry_sign: **Error( severity 5 )**: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'time' (*WordPress.Security.EscapeOutput.OutputNotEscaped*).

2021-03-23 18:02 UTC, gudmdharalds-a8c commented on bla-7.php
> +echo '3988';echo "foo" . time() . PHP_EOL;
:no_entry_sign: **Error( severity 5 )**: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'time' (*WordPress.Security.EscapeOutput.OutputNotEscaped*).

2021-03-23 18:02 UTC, gudmdharalds-a8c commented on bla-8.php
> +echo "foo" . time() . PHP_EOL;
:no_entry_sign: **Error( severity 5 )**: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'time' (*WordPress.Security.EscapeOutput.OutputNotEscaped*).

2021-03-23 18:12 UTC, gudmdharalds-a8c requested changes
**phpcs** scanning turned up:

:no_entry_sign: 1 error 

***


This bot provides automated PHP Linting and PHPCS scanning, read more [here](https://vip.wordpress.com/documentation/the-vip-code-analysis-bot/).

2021-03-23 18:12 UTC, gudmdharalds-a8c commented on bla-7.php
> +echo '3988';echo "foo" . time() . PHP_EOL;
:no_entry_sign: **Error( severity 5 )**: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'time' (*WordPress.Security.EscapeOutput.OutputNotEscaped*).

2021-03-23 18:13 UTC, gudmdharalds-a8c requested changes
**phpcs** scanning turned up:

:no_entry_sign: 1 error 

***


This bot provides automated PHP Linting and PHPCS scanning, read more [here](https://vip.wordpress.com/documentation/the-vip-code-analysis-bot/).

2021-03-23 18:13 UTC, gudmdharalds-a8c commented on bla-8.php
> +echo "foo" . time() . PHP_EOL;
:no_entry_sign: **Error( severity 5 )**: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'time' (*WordPress.Security.EscapeOutput.OutputNotEscaped*).

2021-03-23 18:16 UTC, gudmdharalds-a8c requested changes
**phpcs** scanning turned up:

:no_entry_sign: 8 errors 

***


This bot provides automated PHP Linting and PHPCS scanning, read more [here](https://vip.wordpress.com/documentation/the-vip-code-analysis-bot/).

2021-03-23 18:16 UTC, gudmdharalds-a8c commented on bla-7.php
> +echo "foo" . time() . PHP_EOL;
:no_entry_sign: **Error( severity 5 )**: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'time' (*WordPress.Security.EscapeOutput.OutputNotEscaped*).

2021-03-23 18:16 UTC, gudmdharalds-a8c commented on bla-7.php
> +echo "foo" . time() . PHP_EOL;
:no_entry_sign: **Error( severity 5 )**: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'time' (*WordPress.Security.EscapeOutput.OutputNotEscaped*).

2021-03-23 18:16 UTC, gudmdharalds-a8c commented on bla-7.php
> +echo "foo" . time() . PHP_EOL;
:no_entry_sign: **Error( severity 5 )**: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'time' (*WordPress.Security.EscapeOutput.OutputNotEscaped*).

2021-03-23 18:16 UTC, gudmdharalds-a8c commented on bla-7.php
> +echo '92';echo "foo" . time() . PHP_EOL;
:no_entry_sign: **Error( severity 5 )**: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'time' (*WordPress.Security.EscapeOutput.OutputNotEscaped*).

2021-03-23 18:16 UTC, gudmdharalds-a8c commented on bla-7.php
> +echo '1110';echo "foo" . time() . PHP_EOL;
:no_entry_sign: **Error( severity 5 )**: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'time' (*WordPress.Security.EscapeOutput.OutputNotEscaped*).

2021-03-23 18:16 UTC, gudmdharalds-a8c commented on bla-7.php
> +echo '2780';echo "foo" . time() . PHP_EOL;
:no_entry_sign: **Error( severity 5 )**: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'time' (*WordPress.Security.EscapeOutput.OutputNotEscaped*).

2021-03-23 18:16 UTC, gudmdharalds-a8c commented on bla-7.php
> +echo '3988';echo "foo" . time() . PHP_EOL;
:no_entry_sign: **Error( severity 5 )**: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'time' (*WordPress.Security.EscapeOutput.OutputNotEscaped*).

2021-03-23 18:16 UTC, gudmdharalds-a8c commented on bla-8.php
> +echo "foo" . time() . PHP_EOL;
:no_entry_sign: **Error( severity 5 )**: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'time' (*WordPress.Security.EscapeOutput.OutputNotEscaped*).

2021-04-09 16:49 UTC, gudmdharalds-a8c requested changes
**phpcs** scanning turned up:

:no_entry_sign: 2 errors 

***


This bot provides automated PHP Linting and PHPCS scanning, read more [here](https://vip.wordpress.com/documentation/the-vip-code-analysis-bot/).

2021-04-09 16:49 UTC, gudmdharalds-a8c commented on bla-7.php
> +echo '3988';echo "foo" . time() . PHP_EOL;
:no_entry_sign: **Error( severity 5 )**: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'time' (*WordPress.Security.EscapeOutput.OutputNotEscaped*).

2021-04-09 16:49 UTC, gudmdharalds-a8c commented on bla-8.php
> +echo "foo" . time() . PHP_EOL;
:no_entry_sign: **Error( severity 5 )**: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found 'time' (*WordPress.Security.EscapeOutput.OutputNotEscaped*).

2021-04-15 14:38 UTC, closed without merging

2021-04-19 15:58 UTC, gudmdharalds commented
test